name: Bug report Yaml 🐞
description: Report a bug found in Eclipse Che
title: "Bug:"
labels: [kind/bug]



body:
  - type: markdown
    attributes:
      value: |
        To make it easier for us to help you, please include as much useful information as possible.
        Useful Links:
        
          - Documentation: https://www.eclipse.org/che/docs
          - Contributing: https://github.com/eclipse/che/blob/master/CONTRIBUTING.md
      
        Eclipse Che has public chat on:
          - Mattermost: https://mattermost.eclipse.org/eclipse/channels/eclipse-che

        Before opening a new issue, please search existing issues https://github.com/eclipse/che/issues
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug
    validations:
      required: true
     
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
          

